
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 3
	#The name of the modpack
	modpackName = "Apocryphus"
	#The version of the modpack
	modpackVersion = "v0.03"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

